version = 0.1

[default]
[default.deploy]
stack_name = "bot-backoffice-backend-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true