AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bot-backoffice-backend

  Sample SAM Template for bot-backoffice-backend


Globals:
  Api:
      Cors:
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        AllowCredentials: '''*'''
        AllowMethods: '''*'''
  Function:
    Timeout: 300
    Environment:
        Variables:
          ENV: !Ref Environment
          REGION_COGNITO: !Sub '{{resolve:ssm:/rdcmanager-backoffice-${Environment}/regionCognito}}'
          POOLS_USER_ID: !Sub '{{resolve:ssm:/rdcmanager-backoffice-${Environment}/poolsUserId}}'
          POOLS_WEB_CLINT_ID: !Sub '{{resolve:ssm:/rdcmanager-backoffice-${Environment}/poolsWebClintId}}'

Parameters:
  Environment:
    Type: String

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "LambdaRoleBackoffice-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::293854028872:policy/access2Parameter

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Environment}
      Cors:
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        AllowCredentials: '''*'''
        AllowMethods: '''*'''
      Auth:
          DefaultAuthorizer: MyAuthorizer
          AddDefaultAuthorizerToCorsPreflight: false
          Authorizers:
            MyAuthorizer:
              FunctionArn: !GetAtt Authorizer.Arn
        
  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: utils/authorizer/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
  
  CategoriesGetAll:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_get_all/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesGetAll:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categories
            Method: get
  CategoriesGetAllPending:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_get_all_pending/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesGetAllPending:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesPending
            Method: get
  CategoriesGetAllTypes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_get_all_types/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesGetAllTypes:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesTypes
            Method: get
  CategoriesGetLastCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_get_last_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesGetLastCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesLast
            Method: get
  CategoriesGetOneCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_get_one_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesGetOneCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesOne
            Method: get
  CategoriesSearchCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_get_search_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesSearchCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesSearch
            Method: get
  CategoriesCreateOneCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_create_one_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesCreateOneCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesAdd
            Method: post
  CategoriesDeleteOneCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_delete_one_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesDeleteOneCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesDelete
            Method: post
  CategoriesUpdateOneCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_update_one_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesUpdateOneCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesUpdate
            Method: post
  CategoriesValidateOneCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_validate_one_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesValidateOneCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriesValidate
            Method: post

  PathologiesGetSearchPathology:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pathologies_get_search_pathology/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        PathologiesGetSearchPathology:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /pathologiesSearch
            Method: get
  PathologiesGetSearchPathologyByOrpha:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pathologies_get_search_pathology_by_orpha/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        PathologiesGetSearchPathologyByOrpha:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /pathologiesSearchbyorpha
            Method: get
  PathologiesGetSearchPathologyByOmim:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pathologies_get_search_pathology_by_omim/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        PathologiesGetSearchPathologyByOmim:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /pathologiesSearchbyomim
            Method: get
  PathologiesGetSearchByCategoryPathology:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pathologies_get_search_by_category_pathology/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        PathologiesGetSearchByCategoryPathology:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /pathologiesSearchbycategory
            Method: get
  PathologiesGetSearchByTwoSymptomsPathology:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pathologies_get_search_by_two_symptoms_pathology/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        PathologiesGetSearchByTwoSymptomsPathology:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /pathologiesSearchbytwosymptoms
            Method: get
  PathologiesGetSearchByThreeSymptomsPathology:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pathologies_get_search_by_three_symptoms_pathology/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        PathologiesGetSearchByThreeSymptomsPathology:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /pathologiesSearchbythreesymptoms
            Method: get
  
  SymptomsGetAllSymptomsCategoryPending:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: symptoms_get_all_symptoms_category_pending/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        SymptomsGetAllSymptomsCategoryPending:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /symptomsCategoryPending
            Method: get
  SymptomsGetSearchByCategorySymptom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: symptoms_get_search_by_category_symptom/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        SymptomsGetSearchByCategorySymptom:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /symptomsSearchbycategory
            Method: get
            
  CategoriesCategoriesGetTheCategoriesForCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_categories_get_the_categories_for_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesCategoriesGetTheCategoriesForCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_cat
            Method: get  
  CategoriesCategoriesGetAllSubcategoriesOfCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_categories_get_all_subcategories_of_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesCategoriesGetAllSubcategoriesOfCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_catSubcategories
            Method: get  
  CategoriesCategoriesGetAllPending:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_categories_get_all_pending/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesCategoriesGetAllPending:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_catPending
            Method: get  
  CategoriesCategoriesAddOneCategoryToCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_categories_add_one_category_to_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesCategoriesAddOneCategoryToCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_catAdd
            Method: post  
  CategoriesCategoriesRemoveOneCategoryFromCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_categories_remove_one_category_from_category/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesCategoriesRemoveOneCategoryFromCategory:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_catDelete
            Method: post  
  CategoriesCategoriesValidateOneRelation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_categories_validate_one_relation/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesCategoriesValidateOneRelation:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_catValidate
            Method: post  
  CategoriesSymptomsGetTheCategoriesforSymptom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_symptoms_get_the_categories_for_symptom/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesSymptomsGetTheCategoriesforSymptom:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_sym
            Method: get 
  CategoriesSymptomsAddOneCategoryToSymptom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_symptoms_add_one_category_to_symptom/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesSymptomsAddOneCategoryToSymptom:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_symAdd
            Method: post 
  CategoriesSymptomsRemoveOneCategoryFromSymptom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_symptoms_remove_one_category_from_symptom/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesSymptomsRemoveOneCategoryFromSymptom:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /cat_symDelete
            Method: post 

  CategoriesTranslationsGetOne:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_translations_get_one/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesTranslationsGetOne:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriestranslationsgetone
            Method: get
  CategoriesTranslationsCreateOne:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_translations_create_one/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesTranslationsCreateOne:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriestranslationscreateone
            Method: post
  CategoriesTranslationsUpdateOne:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_translations_update_one/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesTranslationsUpdateOne:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriestranslationsupdateone
            Method: post
  CategoriesTranslationsDeleteOne:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories_translations_delete_one/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
        CategoriesTranslationsDeleteOne:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /categoriestranslationsdeleteone
            Method: post
  
## New Refactor
  Pathologies:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pathologies/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
          Pathologies:
            Type: Api 
            Properties:
              RestApiId: !Ref MyApi
              Path: /pathologies
              Method: POST

  Symptoms:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: symptoms/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
          Symptoms:
            Type: Api 
            Properties:
              RestApiId: !Ref MyApi
              Path: /symptoms
              Method: POST

  Categories:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categories/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-2:293854028872:layer:psql_layer:4
      Architectures:
        - x86_64
      Events:
          Categories:
            Type: Api 
            Properties:
              RestApiId: !Ref MyApi
              Path: /categories
              Method: POST